name: Bug report
description: Report a problem with the card
title: "[Bug]: "
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue.

        To help debugging quickly, if possible:
        - update to the latest release
        - hard refresh browser cache
        - test once more
  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-check
      options:
        - label: I am using the latest card release
          required: false
        - label: I did a hard refresh and tested again
          required: false
  - type: input
    id: card-version
    attributes:
      label: Card version
      description: Version shown in browser console when the card loads
      placeholder: e.g. 0.2.0
  - type: input
    id: ha-version
    attributes:
      label: Home Assistant version
      placeholder: e.g. 2026.2.0
  - type: input
    id: integration-version
    attributes:
      label: Integration version
      description: tp-link integration version (and omada version if relevant)
      placeholder: e.g. home-assistant-tplink-router 2.18.0
  - type: input
    id: router-model
    attributes:
      label: Router model and firmware
      placeholder: e.g. Archer BE230 v1.0 / Firmware 1.2.5
  - type: markdown
    attributes:
      value: |
        ## Diagnostics export (recommended)

        Please include diagnostics JSON from the card when possible:
        1. Open the card
        2. Double click the card title (this reveals a hidden diagnostics button)
        3. Click the small download icon
        4. Attach the downloaded JSON file to this issue (drag and drop)
  - type: dropdown
    id: diagnostics-status
    attributes:
      label: Diagnostics attachment status
      description: Optional, but strongly recommended for faster troubleshooting
      options:
        - Attached
        - Not attached yet
        - Could not generate
  - type: textarea
    id: diagnostics
    attributes:
      label: Diagnostics JSON
      description: If attached, include the filename and any notes. If not attached, briefly explain why.
      placeholder: |
        Attached file: tplink-router-card-export-....json
        Notes: ...
  - type: textarea
    id: steps
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Add card
        2. Select router entry
        3. ...
    validations:
      required: true
  - type: textarea
    id: actual
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: expected
    attributes:
      label: What did you expect to happen?
  - type: textarea
    id: logs
    attributes:
      label: Console logs (optional)
      description: Browser console logs related to this card
      render: shell
  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots or recordings (optional)
      description: Drag and drop images or videos here
