name: Feature request
description: Suggest a new feature or improvement
title: "[Feature]: "
labels:
  - enhancement
body:
  - type: textarea
    id: problem
    attributes:
      label: Problem to solve
      description: What is difficult today?
      placeholder: I cannot...
    validations:
      required: true
  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What should be added or changed?
    validations:
      required: true
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      description: Any workaround or alternative approach you tried
  - type: textarea
    id: context
    attributes:
      label: Extra context
      description: Screenshots, examples, related entities, model/firmware details
